"""
Type stubs for LogXide - High-performance logging for Python
"""

import logging as _stdlib_logging
from collections.abc import MutableMapping
from typing import IO, Any, Callable, Generic, TypeVar, overload

# Version information
__version__: str
__author__: str
__email__: str
__license__: str
__description__: str
__url__: str

# Logging levels
DEBUG: int
INFO: int
WARNING: int
WARN: int  # Alias for WARNING
ERROR: int
CRITICAL: int
FATAL: int  # Alias for CRITICAL
NOTSET: int

# Type aliases
LogLevel = int

_L = TypeVar("_L")

class PyLogger(_stdlib_logging.Logger):
    """High-performance logger implementation."""

    def __init__(self, name: str) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def level(self) -> int: ...
    @property
    def handlers(self) -> list[Any]: ...
    @property
    def manager(self) -> Any: ...
    @property
    def disabled(self) -> bool: ...
    @property
    def filters(self) -> list[Any]: ...
    @property
    def propagate(self) -> bool: ...
    @propagate.setter
    def propagate(self, value: bool) -> None: ...
    @property
    def parent(self) -> PyLogger | None: ...
    @parent.setter
    def parent(self, value: PyLogger | None) -> None: ...
    def setLevel(self, level: LogLevel) -> None: ...
    def getEffectiveLevel(self) -> int: ...
    def addHandler(self, handler: Any) -> None: ...
    def removeHandler(self, handler: Any) -> None: ...
    def addFilter(self, filter: Any) -> None: ...
    def removeFilter(self, filter: Any) -> None: ...
    def disable(self, level: LogLevel) -> None: ...
    def setFormatter(self, formatter: Any) -> None: ...
    def getChild(self, suffix: str) -> PyLogger: ...
    def isEnabledFor(self, level: LogLevel) -> bool: ...
    def debug(self, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def info(self, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def warning(self, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def error(self, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def critical(self, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def exception(self, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def log(self, level: LogLevel, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def fatal(self, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def warn(self, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def hasHandlers(self) -> bool: ...
    def getChildren(self) -> list[Any]: ...
    def makeRecord(
        self,
        name: str,
        level: int,
        fn: str,
        lno: int,
        msg: str,
        args: tuple[Any, ...] | dict[str, Any] | None,
        exc_info: Any,
    ) -> LogRecord: ...
    def handle(self, record: LogRecord) -> None: ...
    def callHandlers(self, record: LogRecord) -> None: ...
    def findCaller(self, stack_info: bool = False) -> tuple[str, int, str, Any]: ...
    @property
    def root(self) -> PyLogger: ...
    def filter(self, record: LogRecord) -> bool: ...

# Type alias for Logger
Logger = PyLogger

class LogRecord:
    """Log record with all standard attributes."""

    name: str
    levelno: int
    levelname: str
    pathname: str
    filename: str
    module: str
    lineno: int
    msg: str
    args: tuple[Any, ...] | dict[str, Any] | None
    exc_info: Any
    funcName: str
    func_name: str
    stack_info: str | None
    sinfo: str | None
    created: float
    msecs: float
    relativeCreated: float
    thread: int | None
    threadName: str | None
    process: int
    processName: str
    message: str
    asctime: str
    exc_text: str | None
    task_name: str | None
    extra: dict[str, Any] | None

    def __init__(
        self,
        name: str,
        level: int,
        pathname: str,
        lineno: int,
        msg: str,
        args: tuple[Any, ...] | dict[str, Any] | None,
        exc_info: Any,
        func: str | None = None,
        sinfo: str | None = None,
        **kwargs: Any,
    ) -> None: ...
    def getMessage(self) -> str: ...

class Filter:
    """Filter implementation for compatibility."""

    name: str
    nlen: int

    def __init__(self, name: str = "") -> None: ...
    def filter(self, record: LogRecord) -> bool: ...

class LoggerAdapter(_stdlib_logging.LoggerAdapter[_L]):
    """Adapter for loggers with contextual information."""

    logger: _L
    extra: dict[str, Any] | None
    merge_extra: bool

    def __init__(
        self, logger: _L, extra: dict[str, Any] | None = None, merge_extra: bool = False
    ) -> None: ...
    def __class_getitem__(cls, item: Any) -> Any: ...
    def process(self, msg: Any, kwargs: MutableMapping[str, Any]) -> tuple[Any, MutableMapping[str, Any]]: ...
    def debug(self, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def info(self, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def warning(self, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def warn(self, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def error(self, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def critical(self, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def exception(self, msg: Any, *args: Any, exc_info: bool = True, **kwargs: Any) -> None: ...
    def fatal(self, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def log(self, level: LogLevel, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def isEnabledFor(self, level: LogLevel) -> bool: ...
    def setLevel(self, level: LogLevel) -> None: ...
    def getEffectiveLevel(self) -> int: ...
    def hasHandlers(self) -> bool: ...
    @property
    def manager(self) -> Any: ...
    @manager.setter
    def manager(self, value: Any) -> None: ...
    @property
    def name(self) -> str: ...

class NullHandler:
    """A handler that does nothing."""

    def __init__(self) -> None: ...
    def handle(self, record: LogRecord) -> None: ...
    def emit(self, record: LogRecord) -> None: ...
    def setLevel(self, level: LogLevel) -> None: ...
    def setFormatter(self, formatter: Any) -> None: ...
    def __call__(self, record: LogRecord) -> None: ...

class Formatter:
    """Formatter class."""

    fmt: str
    datefmt: str | None

    def __init__(
        self,
        fmt: str | None = None,
        datefmt: str | None = None,
        style: str = "%",
        validate: bool = True,
        **kwargs: Any,
    ) -> None: ...
    def format(self, record: LogRecord) -> str: ...
    def formatTime(self, record: LogRecord, datefmt: str | None = None) -> str: ...
    def formatException(self, ei: tuple[Any, ...]) -> str: ...
    def formatStack(self, stack_info: str) -> str: ...

class ColorFormatter(Formatter):
    """Formatter with ANSI color support."""

    def __init__(
        self,
        fmt: str | None = None,
        datefmt: str | None = None,
        style: str = "%",
        validate: bool = True,
        **kwargs: Any,
    ) -> None: ...
    def format(self, record: LogRecord) -> str: ...

class Handler:
    """Handler base class."""

    formatter: Formatter | None
    level: int
    terminator: str
    filters: list[Any]

    def __init__(self, level: LogLevel = ...) -> None: ...
    def handle(self, record: LogRecord) -> bool: ...
    def emit(self, record: LogRecord) -> None: ...
    def filter(self, record: LogRecord) -> bool: ...
    def addFilter(self, filter: Any) -> None: ...
    def removeFilter(self, filter: Any) -> None: ...
    def setFormatter(self, formatter: Formatter) -> None: ...
    def setLevel(self, level: LogLevel) -> None: ...
    def handleError(self, record: LogRecord) -> None: ...
    def format(self, record: LogRecord) -> str: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
    @property
    def name(self) -> str | None: ...
    @name.setter
    def name(self, value: str | None) -> None: ...
    def __call__(self, record: LogRecord) -> None: ...

class StreamHandler(Handler):
    """Stream handler class."""

    def __init__(self, stream: IO[str] | None = None) -> None: ...
    def emit(self, record: LogRecord) -> None: ...
    def flush(self) -> None: ...
    def setStream(self, stream: IO[str]) -> IO[str] | None: ...
    @property
    def stream(self) -> IO[str]: ...
    @stream.setter
    def stream(self, value: IO[str]) -> None: ...

class FileHandler(StreamHandler):
    """File handler class."""

    baseFilename: str
    mode: str
    encoding: str | None
    delay: bool

    def __init__(
        self,
        filename: str,
        mode: str = "a",
        encoding: str | None = None,
        delay: bool = False,
    ) -> None: ...

class RotatingFileHandler(Handler):
    """Rotating file handler class."""

    baseFilename: str
    mode: str
    maxBytes: int
    backupCount: int
    encoding: str | None
    delay: bool

    def __init__(
        self,
        filename: str,
        mode: str = "a",
        maxBytes: int = 0,
        backupCount: int = 0,
        encoding: str | None = None,
        delay: bool = False,
    ) -> None: ...
    def doRollover(self) -> None: ...

class LoggingManager:
    """Mock logging manager for compatibility."""

    def __init__(self) -> None: ...
    disable: int

class _LoggingModule:
    """The main logging module interface."""

    # Static methods
    @staticmethod
    def getLogger(name: str | None = None) -> PyLogger: ...
    @staticmethod
    def basicConfig(**kwargs: Any) -> None: ...
    @staticmethod
    def flush() -> None: ...
    @staticmethod
    def register_python_handler(handler: Callable[..., Any]) -> None: ...
    @staticmethod
    def addLevelName(level: LogLevel, levelName: str) -> None: ...
    @overload
    @staticmethod
    def getLevelName(level: int) -> str: ...
    @overload
    @staticmethod
    def getLevelName(level: str) -> int | str: ...
    @staticmethod
    def getLevelName(level: int | str) -> int | str: ...
    @staticmethod
    def disable(level: LogLevel) -> None: ...
    @staticmethod
    def getLoggerClass() -> type[PyLogger]: ...
    @staticmethod
    def setLoggerClass(klass: type[PyLogger]) -> None: ...
    @staticmethod
    def captureWarnings(capture: bool) -> None: ...
    @staticmethod
    def makeLogRecord(dict: dict[str, Any]) -> LogRecord: ...
    @staticmethod
    def getLogRecordFactory() -> type[LogRecord]: ...
    @staticmethod
    def setLogRecordFactory(factory: type[LogRecord]) -> None: ...
    @staticmethod
    def getLevelNamesMapping() -> dict[str, int]: ...
    @staticmethod
    def getHandlerByName(name: str) -> Any: ...
    @staticmethod
    def getHandlerNames() -> list[str]: ...

    # Module-level logging functions
    @staticmethod
    def debug(msg: Any, *args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def info(msg: Any, *args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def warning(msg: Any, *args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def error(msg: Any, *args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def critical(msg: Any, *args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def exception(msg: Any, *args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def log(level: LogLevel, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def fatal(msg: Any, *args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def warn(msg: Any, *args: Any, **kwargs: Any) -> None: ...

    # Level constants
    DEBUG: int
    INFO: int
    WARNING: int
    WARN: int
    ERROR: int
    CRITICAL: int
    FATAL: int
    NOTSET: int

    # Classes
    PyLogger: type[PyLogger]
    Logger: type[PyLogger]
    LogRecord: type[LogRecord]
    Filter: type[Filter]
    LoggerAdapter: type[LoggerAdapter[Any]]
    NullHandler: type[NullHandler]
    Formatter: type[Formatter]
    Handler: type[Handler]
    StreamHandler: type[StreamHandler]
    FileHandler: type[FileHandler]
    RotatingFileHandler: type[RotatingFileHandler]
    LoggingManager: type[LoggingManager]

    # Attributes
    root: PyLogger
    lastResort: NullHandler
    raiseExceptions: bool
    BASIC_FORMAT: str

# The main logging module instance
logging: _LoggingModule

# Core functions
def getLogger(name: str | None = None) -> PyLogger: ...
def basicConfig(**kwargs: Any) -> None: ...
def flush() -> None: ...
def register_python_handler(handler: Callable[..., Any]) -> None: ...

# Compatibility functions
def addLevelName(level: LogLevel, levelName: str) -> None: ...
@overload
def getLevelName(level: int) -> str: ...
@overload
def getLevelName(level: str) -> int | str: ...
def getLevelName(level: int | str) -> int | str: ...
def disable(level: LogLevel) -> None: ...
def getLoggerClass() -> type[PyLogger]: ...
def setLoggerClass(klass: type[PyLogger]) -> None: ...
def captureWarnings(capture: bool) -> None: ...
def makeLogRecord(dict: dict[str, Any]) -> LogRecord: ...
def getLogRecordFactory() -> type[LogRecord]: ...
def setLogRecordFactory(factory: type[LogRecord]) -> None: ...
def getLevelNamesMapping() -> dict[str, int]: ...
def getHandlerByName(name: str) -> Any: ...
def getHandlerNames() -> list[str]: ...
def set_thread_name(name: str) -> None: ...
def clear_handlers() -> None: ...

# Installation functions

def uninstall() -> None:
    """Restore the standard logging module."""
    ...
